import Script from "next/script";

function Head() {
  return (
    <>
      <title>Home - Adison Cavani</title>
      <meta name="description" content="Generated by create next app" />

      <meta content="width=device-width, initial-scale=1" name="viewport" />

      <link href="/static/favicons/favicon.ico" rel="shortcut icon" />
      <link href="/static/favicons/site.webmanifest" rel="manifest" />
      <link
        href="/static/favicons/apple-touch-icon.png"
        rel="apple-touch-icon"
        sizes="180x180"
      />
      <link
        href="/static/favicons/favicon-32x32.png"
        rel="icon"
        sizes="32x32"
        type="image/png"
      />
      <link
        href="/static/favicons/favicon-16x16.png"
        rel="icon"
        sizes="16x16"
        type="image/png"
      />
      <link
        color="#4a9885"
        href="/static/favicons/safari-pinned-tab.svg"
        rel="mask-icon"
      />
      <meta content="#ffffff" name="theme-color" />
      <meta content="#ffffff" name="msapplication-TileColor" />
      <meta
        content="/static/favicons/browserconfig.xml"
        name="msapplication-config"
      />

      {process.env.NODE_ENV === "production" && (
        <Script
          type="application/javascript"
          data-domain="adison.me"
          src="https://analytics.adison.me/js/script.js"
          strategy="lazyOnload"
        />
      )}
    </>
  );
}

export default Head;
